version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT:-8080}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    # depends_on:
    #   - db

  # db:
  #   image: postgres:13-alpine
  #   container_name: task-manager-db
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-user}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #     POSTGRES_DB: ${POSTGRES_DB:-taskdb}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  postgres_data:
    driver: local
