apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend
  labels:
    app: task-manager-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: task-manager-backend
