pipeline {
    agent any

    environment {
        DATABASE_URL = credentials('DATABASE_URL')
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        GITHUB_TOKEN = credentials('github-token')
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    def branch = env.BRANCH_NAME == 'dev' ? 'dev' : 'main'
                    git branch: branch, url: 'https://github.com/saiiru/task-manager-app.git', credentialsId: 'github-token'
                }
            }
        }

        stage('Build and Test Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        sh 'docker buildx create --use'
                        sh 'docker buildx build --platform linux/amd64 -t saiiru/task-manager-backend:latest --target tester --push .'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    docker.image('saiiru/task-manager-backend:latest').inside("-e DATABASE_URL=${env.DATABASE_URL}") {
                        sh 'go test ./...'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            when {
                branch 'dev'
            }
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        sh 'docker buildx build --platform linux/amd64 -t saiiru/task-manager-backend:dev --push .'
                    }
                }
            }
        }

        stage('Deploy to Dev Kubernetes') {
            when {
                branch 'dev'
            }
            steps {
                script {
                    sh 'kubectl apply -f ci-cd/kubernetes/secret.yaml'
                    sh 'kubectl apply -f ci-cd/kubernetes/deployment.yaml'
                    sh 'kubectl apply -f ci-cd/kubernetes/service.yaml'
                }
            }
        }

        stage('Promote to Prod') {
            when {
                branch 'main'
            }
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        sh 'docker buildx build --platform linux/amd64 -t saiiru/task-manager-backend:latest --push .'
                    }
                    sh 'kubectl apply -f ci-cd/kubernetes/secret.yaml'
                    sh 'kubectl apply -f ci-cd/kubernetes/deployment.yaml'
                    sh 'kubectl apply -f ci-cd/kubernetes/service.yaml'
                }
            }
        }
    }
}